# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: handyTOOL's Blog - 带你走进3D的世界
email: squarepants2048@hotmail.com
description: > # this means to ignore newnes until "baseurl:"
  OpenGL, WebGL, Metal ... 研究各种3D技术
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  SquarePants1991

# Custom vars
version:             1.0.0

# Build settings
theme: minimal-mistakes-jekyll
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-archives

markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    default_lang: c

friend_links:
  - title: 简书
    url: http://www.jianshu.com/u/e6367cf15710
  - title: CocoaChina
    url: http://blog.cocoachina.com/621486
  - title: 推酷
    url: http://www.tuicool.com/
  - title: outofmemory
    url: http://outofmemory.cn/
